### ISSUE TITLE
0.10-alpha API changes

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bech32#126]
You can see the documentation for 0.10 at docs.rs: https://docs.rs/bech32/0.10.0-alpha/bech32/index.html

A few comments:

* We have `FromBase32`, `ToBase32`, `WriteBase32`, `WriteBase256`, `CheckBase32` traits. None of these are used anywhere. I think every one of these traits should be dropped.
* If you have an allocator, the `encode` and `decode` functions (and their variants) are available. We should draw attention to these in the main docs. If you want segwit, we should point the user to the `segwit` module.
* If you do *not* have an allocator, we currently have the messy arrayvec-based API with functions like `decode_lowercase` which really aren't useful in the absense of arrayvec.

I propose:

* We drop all the existing traits.
* We expose `primitives::decode::CheckedHrpString` at the top level for non-alloc decoding
* We expose a wrapper for the `data.iter().copied().bytes_to_fes().with_checksum::<Bech32>(&hrp).chars()` iterator chain, and maybe another for the `with_witness_version` variant, at the top level for non-alloc encoding. These wrappers should just take a byte slice. We can document that if you want to use an arbitrary iterator, the `primitives::iter` module will give you the pieces to do so.
* We rewrite the top-level docs to give examples of various things:
   * A normal Bitcoin user probably wants to use the `segwit` module; see examples there.
   * A non-Bitcoin user probably wants to use `encode`/`decode` functions (add example).
   * A non-Bitcoin no-alloc user probably wants to use the `CheckedHrpString` and non-alloc decoding method.
   * If you want to define your own checksum you should use the `Checksum` trait. We should provide an example, maybe of the BIP-93 checksum.
* We should also change all the re-exports to use `#[doc(inline)]` so that they appear as top-level structures rather than re-exports.

**Comment by tcharding** [comment]
Perhaps we can come up with a list of the users we are trying to support because I don't currently know this? The reason I ask is that removing all the `lib.rs` traits basically makes the current top level API useless because it's tightly coupled eg, the `encode` function takes `T: AsRef[u5]` because it was expected that users would use the `ToBase32` trait to convert their `Vec<u8>` to a `&[u5]`.

**Comment by tcharding** [comment]
@clarkmoody this question is kind of for you, you've written a crate this is, from looking at crates.io reasonably widely used, I definitely don't want to come in and annoy all of your users with a bitcoin-first attitude for no reason. But if all those users are just riding on bitcoin anyway then I don't think it matters if we are obviously bitcoin-first as long as we keep supporting them also.

**Comment by apoelstra** [comment]
>Do we want to maintain a top level API that encodes/decodes data without mention of the witness version i.e., non-bitcoin users?

Yes. Even Bitcoin users will use this API e.g. for descriptors and for lightning invoices.

>I'd like to understand why the non-bitcoin usecase comes upfront

We can foreground the "bitcoin" (by which I guess you mean segwit) usecase more. But in general the segwit stuff is in its own module because it's more complicated and is useless for anything except segwit.

**Comment by tcharding** [comment]
> for descriptors and for lightning invoices

That's good enough for me.

> We can foreground the "bitcoin" (by which I guess you mean segwit)

Consider me schooled :)

**Comment by tcharding** [comment]
Your proposed changes sound good to me, I can't comment further on the details without playing with the code though.

**Comment by clarkmoody** [comment]
Proposed changes sound good, and I especially love the idea of removing unused traits 😄

**Comment by clarkmoody** [comment]
We also have an error in `hrp.rs`:

```diff
--- pub fn is_valid_on_regtest(&self) -> bool { *self == self::BC }
+++ pub fn is_valid_on_regtest(&self) -> bool { *self == self::BCRT }
```

**Comment by tcharding** [comment]
#127, 10 minutes after it was reported - like a boss!
