### ISSUE TITLE
Reference to `Hrp::buf` bytes

### ISSUE THREAD

**Issue by thibault-martinez** [rust-bitcoin/rust-bech32#143]
Hello, thanks for the recent updates that allowed us to start using your crate.

Is there a specific reason why there is no direct access to the `Hrp::buf` bytes through something like `AsRef<[u8]>` or a method?
Looks like our only solution at the moment is to use `byte_iter` and collect it when all we need is just a reference.
I'm happy doing a PR myself, let me know.

Thanks in advance!

**Comment by apoelstra** [comment]
@thibault-martinez no reason, I think we just overlooked this. I think it's a great idea to return a reference to the `[u8]`. I think we can also return a `&str` accessor which would use [`str::from_utf8`](https://doc.rust-lang.org/std/str/fn.from_utf8.html) internally. (We could also use `from_utf8_unchecked` but I think the performance benefit from skipping the check on a short ASCII string isn't worth the reviewer cost of using unsafe code.)

**Comment by apoelstra** [comment]
So yes, for my part if you submitted a PR then I'd ACK it. I will also let @clarkmoody chime in since this is his crate, in case he's opposed for some reason.
