### ISSUE TITLE
Usage of cast when `From` is available

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bech32#181]
Using `From` (or `into()`) is easier to read than using casts because it stops devs having to wonder if an data being lost.

We have a few places where we use casts to cast `u8` to `usize`

```rust
            let log1 = LOG[self.0 as usize];
            let log2 = LOG[other.0 as usize];
```

Could be written as:

```rust
            let log1 = LOG[usize::from(self.0)];
            let log2 = LOG[usize::from(other.0)];
```

**Comment by apoelstra** [comment]
Interesting. TIL that `usize` implements `From<u8>` and `From<u16>`. (But not `From` from any other numeric type, and I don't believe `Into` for any numeric types).
