### ISSUE TITLE
Add Default trait to Fe32

### ISSUE THREAD

**Issue by optout21** [rust-bitcoin/rust-bech32#187]
[LDK](https://github.com/lightningdevkit/rust-lightning) uses `u5` from earlier version, and during the upgrade to `Fe32` the `Default` ~~and `Ord`~~ traits were missed ([PR](https://github.com/lightningdevkit/rust-lightning/pull/3181)).

Implementation would be trivial here, it just has to be derived.
PR created to add them (#184).

**Comment by apoelstra** [comment]
I wouldn't mind adding `Default` which returns the zero element but `Ord` definitely does not make sense for a GF32 element.

**Comment by tcharding** [comment]
Closed by #184
