### ISSUE TITLE
Implement CheckBase32 more efficiently for slices

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/rust-bech32#19]
#17 introduces the `CheckBase32` trait which allows to check if all values of a `[u8]` are in the range `0..32` and returns the values of the slice as `T: AsRef<[u5]>`. Currently this can only be implemented for `T=Vec<u5>` because of uncertainties of the memory layout of `u5` ([see discussion](https://www.reddit.com/r/rust/comments/88xvgg/hey_rustaceans_got_an_easy_question_ask_here/dwvk0w9/)). Hopefully rust-lang/rust#43036 will resolve this uncertainty.

If `[u8]` and `[u5]` would be guaranteed to have the same memory layout we could do a simple cast from `&'f [u8]` to `&'f [u5]` after checking that all values are in range and save an allocation.

**Comment by clarkmoody** [comment]
@sgeisler Is this issue still relevant. The code has changed a bit since April of '18 😄

**Comment by sgeisler** [comment]
I guess not. The only place where the trait is used in the library itself is in tests and the only thing it would be useful for otherwise is communicating with bech32 but not u5 aware libraries (which don't exist afaik since it's so easy to just get the u5 type from this lib). Although the language feature I referenced is now stable it would probably take an eternity until our oldest supported rust version can use it. So I guess we can close it, if anyone feels a need for it in the future it can be reopened.
