### ISSUE TITLE
`Hrp` should have a constructor from a `T: Display`

### ISSUE THREAD

**Issue by apoelstra** [rust-bitcoin/rust-bech32#195]
This would allow easy construction from a rust-lightning `RawHrp`. Currently it [allocates a `String`](https://github.com/lightningdevkit/rust-lightning/blob/9bdce47f0e0516e37c89c09f1975dfc06b5870b1/lightning-invoice/src/ser.rs#L117) which is an unnecessary allocation and inconvenient.

**Comment by tcharding** [comment]
How would such a constructor get at the string (bytes) created by the `Display` implementation without allocating a string?

We could add convenience constructors but I don't really see the value, what am I missunderstanding?

```rust
    /// Constructs a `Hrp` for an `hrp` string created by calling `hrp.to_string()`. 
    pub fn from_display(hrp: impl fmt::Display) -> Result<Self, Error> {
        let s = hrp.to_string();
        Self::parse(&s)
    }

    /// Constructs a `Hrp` for an `hrp` string created by calling `hrp.to_string()`. 
    pub fn from_display_unchecked(hrp: impl fmt::Display) -> Self {
        let s = hrp.to_string();
        Self::parse_unchecked(&s)
    }
```

**Comment by apoelstra** [comment]
By implementing a `fmt::Write` backed by an array. I've almost finished this, I'll try to PR shortly.

**Comment by clarkmoody** [comment]
Concept ACK, and cool implementation in #196
