### ISSUE TITLE
Release version 0.7.0

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/rust-bech32#37]
This release includes a major API change due to #35. Are there any changes that we want to bundle with it in 0.7?

- [x] merge version bump #36 
- [x] tag version 0.7.0
- [x] release to crates.io

**Comment by sgeisler** [comment]
Wow, that was fast :tada:

**Comment by clarkmoody** [comment]
Just did a quick pass and tagged all missing old releases.
