### ISSUE TITLE
Nightly build error after merging version bump 0.7.0

### ISSUE THREAD

**Issue by sgeisler** [rust-bitcoin/rust-bech32#38]
Ok, that's interesting, we got a build error after merging #36 :

1. Nightly seems to have shifted under us (since #35 was last tested)
2. But this should have gotten caught by travis. Unfortunately my travis account got flagged for trying to spin up bitcoind for an integrationtest in the RPC repo :man_facepalming:, so travis seems to block my PR build too and GitHub doesn't disable merging if the tests aren't being run at all.

**Comment by clarkmoody** [comment]
Found this in docs:

```rust
let _ = panic::take_hook();
```

Just need to capture the return with `_`.

Addressed in #39
