### ISSUE TITLE
bech32::encode computes incorrect checksum for uppercase HRPs 

### ISSUE THREAD

**Issue by str4d** [rust-bitcoin/rust-bech32#40]
[BIP 173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) states:

> **Uppercase/lowercase**
>
> The lowercase form is used when determining a character's value for checksum purposes.
>
> Encoders MUST always output an all lower-case Bech32 string.

`bech32::encode` verifies the provided HRP is internally consistent, but then ignores the returned case type and uses the HRP directly:

https://github.com/rust-bitcoin/rust-bech32/blob/16bbf7e011ae12d5c434dc57dc7471705e855fbe/src/lib.rs#L384-L385

This causes two issues:

- The encoded string is in mixed-case, which is likely what the caller intended but is invalid per the spec. Either the HRP should be auto-lower-cased, or an error should be returned.
- The encoded string is invalid and cannot be decoded, because the decoder (correctly) lower-cases the HRP before verifying the checksum.

**Comment by clarkmoody** [comment]
Nice catch! I've created a branch to fix.
