### ISSUE TITLE
Store and display more information in error type(s)

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bech32#73]
Didn't look deeply but at least position of the character and unexpected length could be stored.

To stabilize the crate more quickly it may be better to hide the error representation:

```rust
enum ErrorInner {
 // ...
}

pub struct Error {
    inner: ErrorInner,
    // maybe more stuff here
}
```

**Comment by tcharding** [comment]
I think we have got the error code pretty clean with the recent re-write, likely this can be closed.

**Comment by apoelstra** [comment]
I'm going to go ahead and close it. I think Kix may have comments on the new error types but they will be different ones :).
