### ISSUE TITLE
Document features

### ISSUE THREAD

**Issue by Kixunil** [rust-bitcoin/rust-bech32#75]
I saw at least a lack of `doc(cfg(...))` on `std::error::Error` impl there's likely more.

**Comment by tcharding** [comment]
Oh, I just did https://github.com/rust-bitcoin/rust-bech32/pull/88 that adds docsrs cfg like in `rust-bitcoin` but while doing that I attempted to answer the question "do impls need `#[cfg_attr(docsrs, doc(cfg(feature = "std")))]` and came to the conclusion (by building with and without and looking at the HTML) that they did not, am I wrong?

**Comment by Kixunil** [comment]
Are you sure you did it correctly? The last time I checked impl items do have the marker. But even if they didn't I'd argue it's a good idea to add it anyway because if it gets fixed (presumably a bug) then it'll start showing up.

**Comment by tcharding** [comment]
Last time we had a discussion like this I was wrong so please leave it with me and I'll double check.

**Comment by tcharding** [comment]
You were right @Kixunil, again :) I did find a useless usage though.
```rust
#[cfg(feature = "alloc")]
#[cfg_attr(docsrs, doc(cfg(feature = "alloc")))]
extern crate alloc;
```

But the same argument you made about this changing in the future applies so will leave it in.
