### ISSUE TITLE
`convert_bits` Iterator

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-bitcoin/rust-bech32#81]
When writing out an object as a bech32 string via `fmt` it seems we currently have to first encode the `[u8]` into a `Vec<u5>` and only then we can call `encode_without_checksum_to_fmt`. This is a bit wasteful, ISTM it wouldn't take a whole log of change to build a version of `convert_bits` that returns an iterator rather than a Vec, and allows avoiding the intermediate allocation.

**Comment by tcharding** [comment]
I think this has been resolved by the recent crate re-write, likely can be closed.
