### ISSUE TITLE
please add a changelog

### ISSUE THREAD

**Issue by benma** [rust-bitcoin/rust-bech32#83]
Hi

I am using this library, and saw that an update is available from the 0.8.1 release I am currently using. It is good practice to keep a changelog so users know what changed in every release. 

I checked the commit history, so no need to add one for past releases, but consider adding one for future releases.

**Comment by tcharding** [comment]
Sure thing bro, can do. Thanks for prodding us, this is super useful because like everyone I have 15,000 things on at the same time. Please prod me for anything like this major or minor that you come across anywhere in the `rus-bitcoin` org.
