### ISSUE TITLE
Overhaul/audit Error types

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bech32#91]
We have an epic on `rust-bitcoin` to overhaul/audit errors. Would it be useful to do it here first as a test run? 

FTR I do not know exactly what is the optimal error handling strategy so need to learn.

cc @Kixunil

**Comment by Kixunil** [comment]
Starting with simple things does make sense. I'd have to look into it more to suggest specific strategy, which I don't have much time for lately. Perhaps around beginning of April will be a better time for me.

**Comment by tcharding** [comment]
No worries man, I'll work towards polishing the rest of the crate until time permits to do errors. Thanks.

**Comment by apoelstra** [comment]
This blog post seems to have many of the same goals as us and is definitely worth reading https://sabrinajewson.org/blog/errors

**Comment by tcharding** [comment]
This has been implicitly resolved by the crate re-write.
